log_dir: ./logs
working_dir: ./temp
output_data_directory: /mnt/output_directory
lco:
    - 'TILED=YES'
    - 'BLOCKXSIZE=256'
    - 'BLOCKYSIZE=256'
    - 'BIGTIFF=YES'
    - 'COMPRESS=LZW'
s3:
    access_key: s3_access_key
    secret_access_key: s3_secret_access_key
    bucket: s3_bucket
    path: s3_path
    region: s3_region
    public: true